import { createServer } from 'node:http';
import { once } from 'node:events';
import { wave } from '../../../tests/test-site/server.js';
export type YangFixtureMode='normal'|'voices'|'aspects'|'opaque'|'unknown'|'lost'|'image'|'conditional'|'expired';
/** Owned HTML fixture with Yang route/iframe boundaries. It does not prove production markup compatibility. */
export async function startYangFixture(mode:YangFixtureMode='normal'){
  const state={reservations:0,submissions:[] as string[],instruction:'Read every field and choose the correct answer.',instructionStatus:200,auth:'READY',suite:1,acknowledgement:'next' as 'next'|'complete'|'accepted'|'login'};
  const navigation='<nav><a href="/">Задания</a><a href="/profile">Профиль</a></nav><div role="radiogroup"><label role="radio"><input type="radio" value="all">Все</label><label role="radio"><input type="radio" value="active">В работе</label><label role="radio"><input type="radio" value="favourite">Избранное</label></div>';
  const pool=mode==='voices'?'94752008':mode==='aspects'?'94707463':'123';
  const choice=(legend:string,name='')=>`<fieldset><legend>${legend}</legend><label><input type="radio" ${name?`name="${name}"`:''} value="yes">Yes</label><label><input type="radio" ${name?`name="${name}"`:''} value="no">No</label></fieldset>`;
  const buttons=(legend:string)=>`<fieldset><legend>${legend}</legend><button type="button" aria-pressed="false">❌</button><button type="button" aria-pressed="false">⚠️</button><button type="button" aria-pressed="false">💚</button></fieldset>`;
  const media=(id:number)=>`<audio aria-label="Первое" src="/audio.wav?side=left&part=${id}"></audio><audio aria-label="Второе" src="/audio.wav?side=right&part=${id}"></audio>`;
  const forms=()=>mode==='voices'?Array.from({length:5},(_,i)=>`<form><h2>Pair ${i+1}</h2>${media(i)}${choice('Похожи ли голоса по звучанию?')}${choice('Похожа ли манера речи?')}${choice('Итог. Насколько сильно похожи голоса?')}</form>`).join(''):
    mode==='aspects'?`<div id="pagination"><button type="button">1</button><button type="button">2</button><button type="button">3</button></div><div id="parts"></div>`:
    mode==='opaque'?'<form><p>Compare left and right</p><div><button type="button" aria-pressed="false">Left</button><button type="button" aria-pressed="false">Right</button></div></form>':
    mode==='conditional'?`<form><h2>Conditional</h2>${choice('Initial','initial')}<div id="conditional"></div></form>`:
    `<form><h2>Question</h2>${mode==='image'?'<img alt="Test shape" src="/image.png">':''}${choice('Choose one','answer')}<fieldset><legend>Choose all</legend><label><input type="checkbox">Red</label><label><input type="checkbox">Blue</label></fieldset><label>Comment<textarea maxlength="50"></textarea></label><label>Count<input type="number" min="1" max="5" step="1" required></label></form>`;
  const server=createServer(async(request,response)=>{
    const url=new URL(request.url??'/','http://fixture');
    response.setHeader('Cache-Control','no-store');
    if(url.pathname==='/audio.wav'){response.setHeader('Content-Type','audio/wav');response.end(wave());return;}
    if(url.pathname==='/image.png'){response.setHeader('Content-Type','image/png');response.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aC1sAAAAASUVORK5CYII=','base64'));return;}
    if(url.pathname==='/reserve'){state.reservations++;response.writeHead(302,{Location:`/task/${pool}/suite-${state.suite}`});response.end();return;}
    if(url.pathname==='/submit'){state.submissions.push(`suite-${state.suite}`);const lost=mode==='unknown'||mode==='lost';if(!lost)state.suite++;if(state.acknowledgement==='login')state.auth='LOGIN';response.writeHead(200,{'Content-Type':'application/json'});response.end(JSON.stringify({next:lost?null:state.acknowledgement==='next'?`/task/${pool}/suite-${state.suite}`:state.acknowledgement==='login'?'/login':null,notice:state.acknowledgement==='complete'?'Задания закончились':state.acknowledgement==='accepted'?'Ответы приняты':null}));return;}
    response.setHeader('Content-Type','text/html; charset=utf-8');
    const auth=state.auth==='OTP'?'<input autocomplete="one-time-code" aria-label="Code">':state.auth==='LOGIN'?'<input name="login"><input type="password">':null;
    if(auth){response.end(`<!doctype html><body>${auth}</body>`);return;}
    if(url.pathname.startsWith('/instructions/')){response.end(`<!doctype html><iframe src="/instruction-body"></iframe>`);return;}
    if(url.pathname==='/instruction-body'){response.statusCode=state.instructionStatus;response.end(`<!doctype html><h1>Project instruction</h1><p>${state.instruction}</p><details><summary>Example rules</summary><p>All parts must be complete. Overall preference must be chosen before aspect ratings.</p></details>`);return;}
    if(url.pathname==='/denied.html'){response.statusCode=403;response.end('<!doctype html><h1>Access denied</h1><p>This is not an instruction.</p>');return;}
    if(url.pathname.startsWith('/task/')){response.end(`<!doctype html><body>${navigation}<span class="task-info__values-time">${mode==='expired'?'0:00':'20:00'}</span><iframe src="/frame" style="width:100%;height:1600px"></iframe><button id="submit">Отправить</button><script>document.querySelector('#submit').onclick=async()=>{const data=await (await fetch('/submit',{method:'POST'})).json();if(data.next)location.href=data.next;if(data.notice){const status=document.createElement('p');status.textContent=data.notice;document.body.append(status);}};</script></body>`);return;}
    if(url.pathname==='/frame'){
      const aspectTemplate=Array.from({length:3},(_,i)=>`<form><h2>Pair ${i+1}</h2><p>Scenario ${i+1}</p>${media(i)}<fieldset><legend>Какое аудио звучит лучше?</legend><button type="button" aria-pressed="false">Left</button><button type="button" aria-pressed="false">Tie</button><button type="button" aria-pressed="false">Right</button></fieldset>${['Скорость','Качество звука','Интонации','Естественность речи','Ошибки произношения','Приятность голоса'].map(name=>`<section data-aspect="${name}">${buttons(name+' слева')}${buttons(name+' справа')}<div class="comparison"></div></section>`).join('')}<label>Место для замечаний<textarea></textarea></label></form>`);
      response.end(`<!doctype html><body>${forms()}<script>
      const templates=${JSON.stringify(aspectTemplate)};const saved={};let active=0;
      if(document.querySelector('#parts')){document.querySelector('#parts').innerHTML=templates[0];document.querySelector('#pagination').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;saved[active]=document.querySelector('#parts').innerHTML;active=Number(e.target.textContent)-1;document.querySelector('#parts').innerHTML=saved[active]||templates[active];});}
      document.addEventListener('change',e=>{if(e.target.type==='radio'){for(const input of e.target.closest('fieldset').querySelectorAll('input')){input.checked=input===e.target;input.toggleAttribute('checked',input===e.target);}}if(e.target.name==='initial'&&e.target.value==='yes'){document.querySelector('#conditional').innerHTML='<label>Explain<textarea required></textarea></label>';}});
      document.addEventListener('input',e=>{if(e.target.tagName==='TEXTAREA')e.target.textContent=e.target.value;if(e.target.tagName==='INPUT'&&e.target.type!=='radio'&&e.target.type!=='checkbox')e.target.setAttribute('value',e.target.value);});
      document.addEventListener('click',e=>{if(e.target.matches('button[aria-pressed]')){for(const button of e.target.parentElement.querySelectorAll('button[aria-pressed]'))button.setAttribute('aria-pressed',String(button===e.target));const aspect=e.target.closest('[data-aspect]');if(aspect&&!e.target.closest('.comparison')){const groups=aspect.querySelectorAll(':scope > fieldset');const left=groups[0].querySelector('[aria-pressed="true"]');const right=groups[1].querySelector('[aria-pressed="true"]');const comparison=aspect.querySelector('.comparison');if(left&&right&&left.textContent===right.textContent){if(!comparison.children.length)comparison.innerHTML='<fieldset><legend>'+aspect.dataset.aspect+' сравнение</legend><button type="button" aria-pressed="false">Left</button><button type="button" aria-pressed="false">Tie</button><button type="button" aria-pressed="false">Right</button></fieldset>';}else comparison.innerHTML='';}}});
      </script></body>`);return;
    }
    const ongoing=url.searchParams.get('activeTab')==='active';if(ongoing&&state.reservations===0){response.end(`<!doctype html><body>${navigation}<p>Нет заданий в работе</p></body>`);return;}
    response.end(`<!doctype html><body>${navigation}<ul><li><h2>Fixture project</h2><span aria-label="${mode==='voices'||mode==='aspects'?'Аудио':mode==='image'?'Картинки':'Текст'}"></span><span>15,00</span><span> за задание</span><button id="instruction">Инструкция</button><button onclick="location.href='/reserve'">${ongoing?'Продолжить':'Приступить'}</button></li></ul><dialog aria-label="Инструкция"><button onclick="document.querySelector('dialog').close()">Закрыть</button><a href="/instructions/${pool}">Открыть в новой вкладке</a><button id="close">Закрыть</button></dialog><script>document.querySelector('#instruction').onclick=()=>document.querySelector('dialog').showModal();document.querySelector('#close').onclick=()=>document.querySelector('dialog').close();</script></body>`);
  });
  server.listen(0,'127.0.0.1');await once(server,'listening');const url=`http://127.0.0.1:${(server.address() as import('node:net').AddressInfo).port}`;
  return {url,pool,state,close:()=>new Promise<void>(resolve=>{server.closeAllConnections();server.close(()=>resolve());})};
}
